import type { GridRow } from "@/interface/grid.interface";

export const GRID_SAMPLE_DATA: GridRow[] = [
  {
    id: "INV-001",
    customer: "Sarah Kim",
    email: "sarah.kim@example.com",
    role: "구매 관리자",
    status: "승인",
  },
  {
    id: "INV-002",
    customer: "James Lee",
    email: "james.lee@example.com",
    role: "재무 담당",
    status: "대기",
  },
  {
    id: "INV-003",
    customer: "Jessica Park",
    email: "jessica.park@example.com",
    role: "운영 매니저",
    status: "승인",
  },
  {
    id: "INV-004",
    customer: "Michael Jung",
    email: "michael.jung@example.com",
    role: "데이터 분석가",
    status: "보류",
  },
  {
    id: "INV-005",
    customer: "Yuna Choi",
    email: "yuna.choi@example.com",
    role: "영업 리드",
    status: "승인",
  },
  {
    id: "INV-006",
    customer: "Daniel Song",
    email: "daniel.song@example.com",
    role: "프로덕트 오너",
    status: "대기",
  },
  {
    id: "INV-007",
    customer: "Kevin Oh",
    email: "kevin.oh@example.com",
    role: "서비스 운영",
    status: "승인",
  },
  {
    id: "INV-008",
    customer: "Emily Han",
    email: "emily.han@example.com",
    role: "마케팅 매니저",
    status: "보류",
  },
  {
    id: "INV-009",
    customer: "Thomas Yoon",
    email: "thomas.yoon@example.com",
    role: "파트너 관리",
    status: "대기",
  },
  {
    id: "INV-010",
    customer: "Mia Kang",
    email: "mia.kang@example.com",
    role: "CS 매니저",
    status: "승인",
  },

  {
    id: "INV-011",
    customer: "Brian Baek",
    email: "brian.baek@example.com",
    role: "기획자",
    status: "승인",
  },
  {
    id: "INV-012",
    customer: "Jieun Noh",
    email: "jieun.noh@example.com",
    role: "UI 디자이너",
    status: "대기",
  },
  {
    id: "INV-013",
    customer: "Jason Lim",
    email: "jason.lim@example.com",
    role: "백엔드 개발자",
    status: "승인",
  },
  {
    id: "INV-014",
    customer: "Hannah Seo",
    email: "hannah.seo@example.com",
    role: "프론트엔드 개발자",
    status: "보류",
  },
  {
    id: "INV-015",
    customer: "Erin Moon",
    email: "erin.moon@example.com",
    role: "QA 엔지니어",
    status: "대기",
  },
  {
    id: "INV-016",
    customer: "Dylan Jang",
    email: "dylan.jang@example.com",
    role: "플랫폼 운영",
    status: "승인",
  },
  {
    id: "INV-017",
    customer: "Naomi Yoo",
    email: "naomi.yoo@example.com",
    role: "콘텐츠 매니저",
    status: "승인",
  },
  {
    id: "INV-018",
    customer: "Sam Hong",
    email: "sam.hong@example.com",
    role: "보안 담당",
    status: "보류",
  },
  {
    id: "INV-019",
    customer: "David Kim",
    email: "david.kim@example.com",
    role: "인프라 엔지니어",
    status: "대기",
  },
  {
    id: "INV-020",
    customer: "Sophia Bae",
    email: "sophia.bae@example.com",
    role: "HR 매니저",
    status: "승인",
  },

  {
    id: "INV-021",
    customer: "Henry Shin",
    email: "henry.shin@example.com",
    role: "사업 기획",
    status: "승인",
  },
  {
    id: "INV-022",
    customer: "Arin Cho",
    email: "arin.cho@example.com",
    role: "브랜드 매니저",
    status: "대기",
  },
  {
    id: "INV-023",
    customer: "Mark Kwon",
    email: "mark.kwon@example.com",
    role: "데이터 엔지니어",
    status: "승인",
  },
  {
    id: "INV-024",
    customer: "Sophie Hwang",
    email: "sophie.hwang@example.com",
    role: "리서치 매니저",
    status: "보류",
  },
  {
    id: "INV-025",
    customer: "Ethan Ahn",
    email: "ethan.ahn@example.com",
    role: "운영 기획",
    status: "대기",
  },
  {
    id: "INV-026",
    customer: "Harin Jung",
    email: "harin.jung@example.com",
    role: "서비스 기획",
    status: "승인",
  },
  {
    id: "INV-027",
    customer: "Ryan Ryu",
    email: "ryan.ryu@example.com",
    role: "시스템 관리자",
    status: "보류",
  },
  {
    id: "INV-028",
    customer: "Olivia Kim",
    email: "olivia.kim@example.com",
    role: "데이터 기획",
    status: "승인",
  },
  {
    id: "INV-029",
    customer: "Lucas Chae",
    email: "lucas.chae@example.com",
    role: "사업 운영",
    status: "대기",
  },
  {
    id: "INV-030",
    customer: "Isabella Lee",
    email: "isabella.lee@example.com",
    role: "마케팅 전략",
    status: "승인",
  },

  {
    id: "INV-031",
    customer: "Noah Kim",
    email: "noah.kim@example.com",
    role: "프로젝트 매니저",
    status: "보류",
  },
  {
    id: "INV-032",
    customer: "Ella Park",
    email: "ella.park@example.com",
    role: "서비스 운영",
    status: "승인",
  },
  {
    id: "INV-033",
    customer: "Andrew Lee",
    email: "andrew.lee@example.com",
    role: "기술 지원",
    status: "대기",
  },
  {
    id: "INV-034",
    customer: "Grace Choi",
    email: "grace.choi@example.com",
    role: "품질 관리",
    status: "승인",
  },
  {
    id: "INV-035",
    customer: "Leo Yoon",
    email: "leo.yoon@example.com",
    role: "파트너십 매니저",
    status: "보류",
  },
];