import type {AuthorityCountryGroup} from "@/types/country.type.ts";
import type {SelectOption} from "@/types/common.types.ts";

// #. 권역 선택 옵션 목록
export const SIGNUP_AUTHORITY_OPTIONS: SelectOption[] = [
    {value: "default", labelKey: "signup.options.authority.default"},
    {value: "all", labelKey: "signup.options.authority.all"},
    {value: "africa", labelKey: "signup.options.authority.africa"},
    {value: "cis", labelKey: "signup.options.authority.cis"},
    {value: "europe", labelKey: "signup.options.authority.europe"},
    {value: "great_china", labelKey: "signup.options.authority.greatChina"},
    {value: "latin_america", labelKey: "signup.options.authority.latinAmerica"},
    {value: "middle_east", labelKey: "signup.options.authority.middleEast"},
    {value: "north_america", labelKey: "signup.options.authority.northAmerica"},
    {value: "se_asia", labelKey: "signup.options.authority.seAsia"},
    {value: "sw_asia", labelKey: "signup.options.authority.swAsia"},
];

// #. 권역 > 법인 > 국가 기준 국가 데이터 목록
export const COUNTRY_GROUPS: AuthorityCountryGroup[] = [
    {
        authorityCode: "africa",
        corporations: [
            {corporationCode: "SEEA", countries: ["KENYA", "TANZANIA"]},
            {corporationCode: "SEWA", countries: ["GHANA", "NIGERIA", "SENEGAL"]},
        ],
    },
    {
        authorityCode: "cis",
        corporations: [
            {corporationCode: "SERC", countries: ["AZERBAIJAN", "RUSSIA"]},
        ],
    },
    {
        authorityCode: "europe",
        corporations: [
            {corporationCode: "SEAD", countries: ["CROATIA", "SERBIA", "SLOVENIA"]},
            {corporationCode: "SEB", countries: ["ESTONIA", "LATVIA", "LITHUANIA"]},
            {corporationCode: "SEBN", countries: ["BELGIUM", "NETHERLANDS"]},
            {corporationCode: "SECZ", countries: ["CZECH", "SLOVAK"]},
            {corporationCode: "SEF", countries: ["FRANCE"]},
            {corporationCode: "SEH", countries: ["HUNGARY"]},
            {corporationCode: "SEI", countries: ["ITALY", "SPAIN"]},
            {corporationCode: "SEIB", countries: ["PORTUGAL"]},
            {corporationCode: "SEPOL", countries: ["POLAND"]},
            {corporationCode: "SEROM", countries: ["BULGARIA", "ROMANIA"]},
            {corporationCode: "SEUC", countries: ["UKRAINE"]},
            {corporationCode: "SEUK", countries: ["UK"]},
        ],
    },
    {
        authorityCode: "great_china",
        corporations: [
            {corporationCode: "SCIC", countries: ["西部大区", "东北大区", "华南大区", "华北大区", "华东大区"]},
            {corporationCode: "SEHK", countries: ["HONG KONG"]},
            {corporationCode: "SET", countries: ["TAIWAN"]},
        ],
    },
    {
        authorityCode: "latin_america",
        corporations: [
            {corporationCode: "SAMCOL", countries: ["COLOMBIA"]},
            {corporationCode: "SEASA", countries: ["ARGENTINA", "CHILE"]},
            {corporationCode: "SECH", countries: ["BOLIVIA"]},
            {corporationCode: "SEDA", countries: ["BRAZIL"]},
            {corporationCode: "SELA", countries: ["GUATEMALA"]},
            {corporationCode: "SEM", countries: ["PARAGUAY", "MEXICO"]},
            {corporationCode: "SEPR", countries: ["REP. DOMINICANA", "PERU"]},
        ],
    },
    {
        authorityCode: "middle_east",
        corporations: [
            {corporationCode: "IRAN", countries: ["IRAN"]},
            {corporationCode: "SEIL", countries: ["ISRAEL", "PALESTINE"]},
            {corporationCode: "SELV", countries: ["JORDAN"]},
            {corporationCode: "SEMAG", countries: ["LIBYA", "MOROCCO", "TUNISIA"]},
            {corporationCode: "SEPAK", countries: ["PAKISTAN"]},
            {corporationCode: "SESAR", countries: ["SAUDI ARABIA"]},
            {corporationCode: "SETK", countries: ["TURKIYE"]},
            {corporationCode: "SGE", countries: ["BAHRAIN", "KUWAIT", "OMAN", "QATAR", "UAE"]},
        ],
    },
    {
        authorityCode: "north_america",
        corporations: [
            {corporationCode: "SEA", countries: ["USA"]},
            {corporationCode: "SECA", countries: ["CANADA"]},
        ],
    },
    {
        authorityCode: "se_asia",
        corporations: [
            {corporationCode: "SAVINA", countries: ["VIETNAM"]},
            {corporationCode: "SEAU", countries: ["AUSTRALIA"]},
            {corporationCode: "SEIN", countries: ["INDONESIA"]},
            {corporationCode: "SEPCO", countries: ["PHILIPPINES"]},
            {corporationCode: "SESP", countries: ["SINGAPORE"]},
            {corporationCode: "SME", countries: ["MALAYSIA"]},
            {corporationCode: "TSE", countries: ["CAMBODIA", "LAOS", "MYANMAR", "THAILAND"]},
        ],
    },
    {
        authorityCode: "sw_asia",
        corporations: [
            {corporationCode: "BANGLADESH", countries: ["BANGLADESH"]},
            {corporationCode: "NEPAL", countries: ["NEPAL"]},
            {corporationCode: "SIEL", countries: ["INDIA"]},
        ],
    },
];

// #. 법인 코드(데이터 값)와 i18n 번역 키 매핑
export const CORPORATION_LABEL_KEY_BY_CODE: Record<string, string> = {
    SEEA: "signup.options.corporation.seea",
    SEWA: "signup.options.corporation.sewa",
    SERC: "signup.options.corporation.serc",
    SEAD: "signup.options.corporation.sead",
    SEB: "signup.options.corporation.seb",
    SEBN: "signup.options.corporation.sebn",
    SECZ: "signup.options.corporation.secz",
    SEF: "signup.options.corporation.sef",
    SEH: "signup.options.corporation.seh",
    SEI: "signup.options.corporation.sei",
    SEIB: "signup.options.corporation.seib",
    SEPOL: "signup.options.corporation.sepol",
    SEROM: "signup.options.corporation.serom",
    SEUC: "signup.options.corporation.seuc",
    SEUK: "signup.options.corporation.seuk",
    SCIC: "signup.options.corporation.scic",
    SEHK: "signup.options.corporation.sehk",
    SET: "signup.options.corporation.set",
    SAMCOL: "signup.options.corporation.samcol",
    SEASA: "signup.options.corporation.seasa",
    SECH: "signup.options.corporation.sech",
    SEDA: "signup.options.corporation.seda",
    SELA: "signup.options.corporation.sela",
    SEM: "signup.options.corporation.sem",
    SEPR: "signup.options.corporation.sepr",
    IRAN: "signup.options.corporation.iran",
    SEIL: "signup.options.corporation.seil",
    SELV: "signup.options.corporation.selv",
    SEMAG: "signup.options.corporation.semag",
    SEPAK: "signup.options.corporation.sepak",
    SESAR: "signup.options.corporation.sesar",
    SETK: "signup.options.corporation.setk",
    SGE: "signup.options.corporation.sge",
    SEA: "signup.options.corporation.sea",
    SECA: "signup.options.corporation.seca",
    SAVINA: "signup.options.corporation.savina",
    SEAU: "signup.options.corporation.seau",
    SEIN: "signup.options.corporation.sein",
    SEPCO: "signup.options.corporation.sepco",
    SESP: "signup.options.corporation.sesp",
    SME: "signup.options.corporation.sme",
    TSE: "signup.options.corporation.tse",
    BANGLADESH: "signup.options.corporation.bangladesh",
    NEPAL: "signup.options.corporation.nepal",
    SIEL: "signup.options.corporation.siel",
};

// #. 국가 코드(데이터 값)와 i18n 번역 키 매핑
export const COUNTRY_LABEL_KEY_BY_CODE: Record<string, string> = {
    KENYA: "signup.options.country.kenya",
    TANZANIA: "signup.options.country.tanzania",
    GHANA: "signup.options.country.ghana",
    NIGERIA: "signup.options.country.nigeria",
    SENEGAL: "signup.options.country.senegal",
    AZERBAIJAN: "signup.options.country.azerbaijan",
    RUSSIA: "signup.options.country.russia",
    CROATIA: "signup.options.country.croatia",
    SERBIA: "signup.options.country.serbia",
    SLOVENIA: "signup.options.country.slovenia",
    ESTONIA: "signup.options.country.estonia",
    LATVIA: "signup.options.country.latvia",
    LITHUANIA: "signup.options.country.lithuania",
    BELGIUM: "signup.options.country.belgium",
    NETHERLANDS: "signup.options.country.netherlands",
    CZECH: "signup.options.country.czech",
    SLOVAK: "signup.options.country.slovak",
    FRANCE: "signup.options.country.france",
    HUNGARY: "signup.options.country.hungary",
    ITALY: "signup.options.country.italy",
    SPAIN: "signup.options.country.spain",
    PORTUGAL: "signup.options.country.portugal",
    POLAND: "signup.options.country.poland",
    BULGARIA: "signup.options.country.bulgaria",
    ROMANIA: "signup.options.country.romania",
    UKRAINE: "signup.options.country.ukraine",
    UK: "signup.options.country.uk",
    "西部大区": "signup.options.country.westChina",
    "东北大区": "signup.options.country.northeastChina",
    "华南大区": "signup.options.country.southChina",
    "华北大区": "signup.options.country.northChina",
    "华东大区": "signup.options.country.eastChina",
    "HONG KONG": "signup.options.country.hongKong",
    TAIWAN: "signup.options.country.taiwan",
    COLOMBIA: "signup.options.country.colombia",
    ARGENTINA: "signup.options.country.argentina",
    CHILE: "signup.options.country.chile",
    BOLIVIA: "signup.options.country.bolivia",
    BRAZIL: "signup.options.country.brazil",
    GUATEMALA: "signup.options.country.guatemala",
    PARAGUAY: "signup.options.country.paraguay",
    MEXICO: "signup.options.country.mexico",
    "REP. DOMINICANA": "signup.options.country.repDominicana",
    PERU: "signup.options.country.peru",
    IRAN: "signup.options.country.iran",
    ISRAEL: "signup.options.country.israel",
    PALESTINE: "signup.options.country.palestine",
    JORDAN: "signup.options.country.jordan",
    LIBYA: "signup.options.country.libya",
    MOROCCO: "signup.options.country.morocco",
    TUNISIA: "signup.options.country.tunisia",
    PAKISTAN: "signup.options.country.pakistan",
    "SAUDI ARABIA": "signup.options.country.saudiArabia",
    TURKIYE: "signup.options.country.turkiye",
    BAHRAIN: "signup.options.country.bahrain",
    KUWAIT: "signup.options.country.kuwait",
    OMAN: "signup.options.country.oman",
    QATAR: "signup.options.country.qatar",
    UAE: "signup.options.country.uae",
    USA: "signup.options.country.usa",
    CANADA: "signup.options.country.canada",
    VIETNAM: "signup.options.country.vietnam",
    AUSTRALIA: "signup.options.country.australia",
    INDONESIA: "signup.options.country.indonesia",
    PHILIPPINES: "signup.options.country.philippines",
    SINGAPORE: "signup.options.country.singapore",
    MALAYSIA: "signup.options.country.malaysia",
    CAMBODIA: "signup.options.country.cambodia",
    LAOS: "signup.options.country.laos",
    MYANMAR: "signup.options.country.myanmar",
    THAILAND: "signup.options.country.thailand",
    BANGLADESH: "signup.options.country.bangladesh",
    NEPAL: "signup.options.country.nepal",
    INDIA: "signup.options.country.india",
};

